on:
  push:
    tags:
      - 'v*'
    branches: [ master ]
  pull_request:
    branches: [ master ]
name: Build and create release

jobs:
  build:
    name: Build and upload artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build Linux version
        run: dotnet publish -c Release -r linux-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained=true --output ./publish
      - name: 'Gzip artifact'
        run: 'tar -czvf fedora-upgrader.tar.gz ./publish/fedora-upgrader'
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: fedora-upgrader
          path: fedora-upgrader.tar.gz
          if-no-files-found: error
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: false